/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiSubtasksPreviewDialog: typeof import('./src/components/todo/AiSubtasksPreviewDialog.vue')['default']
    AiTaskPreviewDialog: typeof import('./src/components/todo/AiTaskPreviewDialog.vue')['default']
    AttachmentPanel: typeof import('./src/components/attachment/AttachmentPanel.vue')['default']
    AttachmentPreviewDialog: typeof import('./src/components/attachment/AttachmentPreviewDialog.vue')['default']
    DraggableTaskList: typeof import('./src/components/layout/DraggableTaskList.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDatePickerPanel: typeof import('element-plus/es')['ElDatePickerPanel']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GanttView: typeof import('./src/components/layout/GanttView.vue')['default']
    KanbanTaskBucket: typeof import('./src/components/layout/KanbanTaskBucket.vue')['default']
    KanbanView: typeof import('./src/components/layout/KanbanView.vue')['default']
    MinimalCommandInput: typeof import('./src/components/todo/MinimalCommandInput.vue')['default']
    MinimalTaskList: typeof import('./src/components/layout/MinimalTaskList.vue')['default']
    NewTaskDialog: typeof import('./src/components/todo/NewTaskDialog.vue')['default']
    QuickInputBar: typeof import('./src/components/todo/QuickInputBar.vue')['default']
    ResizableImageView: typeof import('./src/components/editor/ResizableImageView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsAiSection: typeof import('./src/components/settings/SettingsAiSection.vue')['default']
    SettingsDataSection: typeof import('./src/components/settings/SettingsDataSection.vue')['default']
    SettingsDialog: typeof import('./src/components/settings/SettingsDialog.vue')['default']
    SettingsEmailGatewaySection: typeof import('./src/components/settings/SettingsEmailGatewaySection.vue')['default']
    SettingsNotificationSection: typeof import('./src/components/settings/SettingsNotificationSection.vue')['default']
    ShortcutKeyInput: typeof import('./src/components/settings/ShortcutKeyInput.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    TaskDetailPanel: typeof import('./src/components/layout/TaskDetailPanel.vue')['default']
    TaskDetailPanelBody: typeof import('./src/components/layout/TaskDetailPanelBody.vue')['default']
    TaskDetailReminderPanel: typeof import('./src/components/layout/TaskDetailReminderPanel.vue')['default']
    TaskDetailSubtasks: typeof import('./src/components/layout/TaskDetailSubtasks.vue')['default']
    TaskListPanel: typeof import('./src/components/layout/TaskListPanel.vue')['default']
    TodoItem: typeof import('./src/components/todo/TodoItem.vue')['default']
    WysiwygEditor: typeof import('./src/components/editor/WysiwygEditor.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
