import type { InjectionKey, Ref } from "vue";
import type { SortableEvent } from "sortablejs";
import type { Category, KanbanColumn, Tag, TodoSummary } from "../../types";
import type { TodoSortField } from "../../utils/sortTodos";
import type { TaskListColumnId } from "../../utils/taskListColumns";

export interface TaskListCellContext {
  isTrashMode: Ref<boolean>;
  minimal: Ref<boolean>;
  categories: Ref<Category[]>;
  tags: Ref<Tag[]>;
  kanbanColumns: Ref<KanbanColumn[]>;
  sortField: Ref<TodoSortField | undefined>;
  sortDirection: Ref<"asc" | "desc" | undefined>;
  highlightId: Ref<number | null>;
  duePopoverId: Ref<number | null>;
  startPopoverId: Ref<number | null>;
  tagPopoverId: Ref<number | null>;
  tagDrafts: Ref<Record<number, number[]>>;
  titleOverflowMap: Ref<Record<number, boolean>>;
  editingTitleId: Ref<number | null>;
  titleDrafts: Ref<Record<number, string>>;
  priorityLabel: Ref<Record<string, string>>;
  onHeaderClick: (prop: string) => void;
  sortIndicator: (prop: string) => string;
  onRowClick: (todo: TodoSummary, event: MouseEvent) => void;
  onToggle: (todo: TodoSummary) => void;
  onTogglePin: (todo: TodoSummary) => void;
  onView: (id: number) => void;
  onEdit: (id: number) => void;
  onDelete: (todo: TodoSummary) => void;
  onRestore: (todo: TodoSummary) => void;
  onTitleUpdate: (todo: TodoSummary, title: string) => void;
  onPriorityUpdate: (todo: TodoSummary, priority: string) => void;
  onDueDateUpdate: (todo: TodoSummary, dueDate: string | null) => void;
  onStartDateUpdate: (todo: TodoSummary, startDate: string | null) => void;
  onTagsUpdate: (todo: TodoSummary, tagIds: number[]) => void;
  onCategoryUpdate: (todo: TodoSummary, categoryId: number | null) => void;
  onKanbanColumnUpdate: (todo: TodoSummary, kanbanColumnId: number | null) => void;
  formatDueDate: (date?: string) => string;
  dueDateValue: (todo: TodoSummary) => string | undefined;
  startDateValue: (todo: TodoSummary) => string | undefined;
  onDuePopoverVisible: (todoId: number, visible: boolean) => void;
  onStartPopoverVisible: (todoId: number, visible: boolean) => void;
  onDueDateChange: (todo: TodoSummary, value: string | undefined) => void;
  onStartDateChange: (todo: TodoSummary, value: string | undefined) => void;
  onTagPopoverVisible: (todo: TodoSummary, visible: boolean) => void;
  onPriorityChange: (todo: TodoSummary, priority: string) => void;
  onCategoryChange: (todo: TodoSummary, command: number | "none") => void;
  onKanbanColumnChange: (todo: TodoSummary, command: number | "none") => void;
  priorityClass: (priority: string) => string;
  categoryPillStyle: (todo: TodoSummary) => Record<string, string> | undefined;
  kanbanPillStyle: (todo: TodoSummary) => Record<string, string> | undefined;
  tagPillStyle: (todo: TodoSummary, index: number) => Record<string, string> | undefined;
  statusLabel: (todo: TodoSummary) => string;
  assigneeLabel: (todo: TodoSummary) => string;
  recurrenceLabel: (todo: TodoSummary) => string;
  formatDateTimeCn: (value?: string | null) => string;
  isTitleEditing: (todoId: number) => boolean;
  displayTitle: (todo: TodoSummary) => string;
  startTitleEdit: (todo: TodoSummary) => void;
  onTitleInput: (todo: TodoSummary, event: Event) => void;
  onTitleKeydown: (todo: TodoSummary, event: KeyboardEvent) => void;
  onTitleBlur: () => void;
  checkTitleOverflow: (event: MouseEvent, id: number) => void;
}

export const TASK_LIST_CELL_CTX: InjectionKey<TaskListCellContext> = Symbol("taskListCellContext");

export type { TaskListColumnId, SortableEvent };
