use std::collections::HashMap;

use chrono::{Duration, Local};

use crate::db::repositories::{
    DataExportSnapshot, ExportTodoItem, RecurrenceConfig, Subtask, TodoDetail, TodoSummary,
};

fn ts(days_ago: i64) -> String {
    (Local::now() - Duration::days(days_ago))
        .format("%Y-%m-%dT%H:%M:%S%:z")
        .to_string()
}

fn date(days_from_today: i64) -> String {
    (Local::now() + Duration::days(days_from_today))
        .format("%Y-%m-%d")
        .to_string()
}

fn summary(
    id: i64,
    title: &str,
    content_text: &str,
    completed: bool,
    priority: &str,
    start_date: Option<&str>,
    due_date: Option<&str>,
    category_id: Option<i64>,
    category_name: Option<&str>,
    category_color: Option<&str>,
    sort_order: i32,
    pinned: bool,
    assignee: &str,
    kanban_column_id: Option<i64>,
    kanban_column_name: Option<&str>,
    kanban_column_color: Option<&str>,
    tag_ids: Vec<i64>,
    tag_names: Vec<&str>,
    tag_colors: Vec<&str>,
    recurrence_json: Option<RecurrenceConfig>,
) -> TodoSummary {
    TodoSummary {
        id,
        title: title.into(),
        content_text: content_text.into(),
        completed,
        priority: priority.into(),
        start_date: start_date.map(str::to_string),
        due_date: due_date.map(str::to_string),
        category_id,
        category_name: category_name.map(str::to_string),
        category_color: category_color.map(str::to_string),
        sort_order,
        pinned,
        assignee: assignee.into(),
        kanban_column_id,
        kanban_column_name: kanban_column_name.map(str::to_string),
        kanban_column_color: kanban_column_color.map(str::to_string),
        created_at: ts(14 - sort_order as i64),
        updated_at: ts(2),
        tag_ids,
        tag_names: tag_names.into_iter().map(str::to_string).collect(),
        tag_colors: tag_colors.into_iter().map(str::to_string).collect(),
        recurrence_json,
    }
}

fn todo(
    summary: TodoSummary,
    content_html: &str,
    subtasks: Vec<Subtask>,
) -> ExportTodoItem {
    ExportTodoItem {
        detail: TodoDetail {
            summary,
            content_html: content_html.into(),
            subtasks,
        },
        attachments: vec![],
    }
}

fn subtask(id: i64, todo_id: i64, title: &str, completed: bool, sort_order: i32) -> Subtask {
    Subtask {
        id,
        todo_id,
        title: title.into(),
        completed,
        sort_order,
        created_at: ts(5),
        updated_at: ts(1),
    }
}

pub fn build_demo_snapshot() -> DataExportSnapshot {
    let exported_at = Local::now().format("%Y-%m-%dT%H:%M:%S%:z").to_string();

    DataExportSnapshot {
        version: 1,
        exported_at,
        categories: vec![
            crate::db::repositories::Category {
                id: 1,
                name: "工作".into(),
                color: "#1677ff".into(),
                icon: None,
                sort_order: 0,
                created_at: ts(30),
                todo_count: 5,
                incomplete_count: 4,
            },
            crate::db::repositories::Category {
                id: 2,
                name: "生活".into(),
                color: "#52c41a".into(),
                icon: None,
                sort_order: 1,
                created_at: ts(30),
                todo_count: 3,
                incomplete_count: 3,
            },
            crate::db::repositories::Category {
                id: 3,
                name: "学习".into(),
                color: "#722ed1".into(),
                icon: None,
                sort_order: 2,
                created_at: ts(30),
                todo_count: 2,
                incomplete_count: 2,
            },
        ],
        tags: vec![
            crate::db::repositories::Tag {
                id: 1,
                name: "紧急".into(),
                color: "#f5222d".into(),
                created_at: ts(30),
                todo_count: 2,
            },
            crate::db::repositories::Tag {
                id: 2,
                name: "本周".into(),
                color: "#fa8c16".into(),
                created_at: ts(30),
                todo_count: 3,
            },
            crate::db::repositories::Tag {
                id: 3,
                name: "会议".into(),
                color: "#13c2c2".into(),
                created_at: ts(30),
                todo_count: 2,
            },
            crate::db::repositories::Tag {
                id: 4,
                name: "生日".into(),
                color: "#eb2f96".into(),
                created_at: ts(30),
                todo_count: 1,
            },
        ],
        kanban_columns: vec![
            crate::db::repositories::KanbanColumn {
                id: 1,
                name: "待办".into(),
                color: "#8c8c8c".into(),
                subtitle: Some("尚未开始".into()),
                sort_order: 0,
                created_at: ts(30),
                todo_count: 4,
            },
            crate::db::repositories::KanbanColumn {
                id: 2,
                name: "进行中".into(),
                color: "#1677ff".into(),
                subtitle: Some("正在推进".into()),
                sort_order: 1,
                created_at: ts(30),
                todo_count: 3,
            },
            crate::db::repositories::KanbanColumn {
                id: 3,
                name: "待验收".into(),
                color: "#52c41a".into(),
                subtitle: Some("等待确认".into()),
                sort_order: 2,
                created_at: ts(30),
                todo_count: 1,
            },
        ],
        todos: vec![
            todo(
                summary(
                    1,
                    "制定 Q3 产品路线图",
                    "梳理核心功能优先级，输出路线图文档并与团队评审确认。",
                    false,
                    "high",
                    Some(&date(-3)),
                    Some(&date(10)),
                    Some(1),
                    Some("工作"),
                    Some("#1677ff"),
                    0,
                    true,
                    "自己",
                    Some(2),
                    Some("进行中"),
                    Some("#1677ff"),
                    vec![1, 2],
                    vec!["紧急", "本周"],
                    vec!["#f5222d", "#fa8c16"],
                    None,
                ),
                "<p>本季度重点：</p><ul><li>任务详情与提醒体验优化</li><li>看板与列表交互统一</li><li>数据备份与迁移完善</li></ul>",
                vec![
                    subtask(1, 1, "收集各模块需求清单", true, 0),
                    subtask(2, 1, "完成路线图初稿", false, 1),
                    subtask(3, 1, "组织评审会议", false, 2),
                ],
            ),
            todo(
                summary(
                    2,
                    "提交本周工作周报",
                    "汇总本周完成事项、风险与下周计划，周五前提交。",
                    false,
                    "medium",
                    Some(&date(-7)),
                    Some(&date(2)),
                    Some(1),
                    Some("工作"),
                    Some("#1677ff"),
                    1,
                    false,
                    "自己",
                    Some(1),
                    Some("待办"),
                    Some("#8c8c8c"),
                    vec![2],
                    vec!["本周"],
                    vec!["#fa8c16"],
                    None,
                ),
                "<p>周报需包含：关键进展、阻塞问题、下周三项重点。</p>",
                vec![],
            ),
            todo(
                summary(
                    3,
                    "团队周会准备",
                    "整理议程、同步项目进度，并提前发送会议材料。",
                    false,
                    "medium",
                    Some(&date(0)),
                    Some(&date(4)),
                    Some(1),
                    Some("工作"),
                    Some("#1677ff"),
                    2,
                    false,
                    "自己",
                    Some(2),
                    Some("进行中"),
                    Some("#1677ff"),
                    vec![2, 3],
                    vec!["本周", "会议"],
                    vec!["#fa8c16", "#13c2c2"],
                    None,
                ),
                "<p>议程建议：上周回顾 / 本周目标 / 风险同步 / 开放讨论。</p>",
                vec![
                    subtask(4, 3, "更新项目进度表", false, 0),
                    subtask(5, 3, "发送会议邀请与材料", false, 1),
                ],
            ),
            todo(
                summary(
                    4,
                    "妈妈生日提醒（农历）",
                    "提前准备礼物和祝福，农历生日当天早上提醒。",
                    false,
                    "high",
                    None,
                    Some("1990-08-15"),
                    Some(2),
                    Some("生活"),
                    Some("#52c41a"),
                    3,
                    true,
                    "自己",
                    Some(1),
                    Some("待办"),
                    Some("#8c8c8c"),
                    vec![4],
                    vec!["生日"],
                    vec!["#eb2f96"],
                    Some(RecurrenceConfig {
                        enabled: true,
                        freq: "yearly".into(),
                        interval: 1,
                        anchor: "dueDate".into(),
                        calendar: "lunar".into(),
                        lunar_month: Some(8),
                        lunar_day: Some(15),
                        is_leap_month: Some(false),
                        first_reminder_date: None,
                        time: "09:00".into(),
                        advance_minutes: 1440,
                        on_complete: "reschedule".into(),
                    }),
                ),
                "<p>提醒事项：订蛋糕、准备红包、确认当天通话时间。</p>",
                vec![],
            ),
            todo(
                summary(
                    5,
                    "预约年度健康体检",
                    "选择体检机构与套餐，预约周末时段。",
                    false,
                    "high",
                    Some(&date(1)),
                    Some(&date(15)),
                    Some(2),
                    Some("生活"),
                    Some("#52c41a"),
                    4,
                    false,
                    "自己",
                    Some(1),
                    Some("待办"),
                    Some("#8c8c8c"),
                    vec![1],
                    vec!["紧急"],
                    vec!["#f5222d"],
                    None,
                ),
                "<p>重点关注：血脂、颈椎、眼科检查。</p>",
                vec![],
            ),
            todo(
                summary(
                    6,
                    "阅读《深入理解计算机系统》",
                    "每周至少阅读一章，并整理读书笔记。",
                    false,
                    "low",
                    Some(&date(-14)),
                    Some(&date(30)),
                    Some(3),
                    Some("学习"),
                    Some("#722ed1"),
                    5,
                    false,
                    "自己",
                    Some(2),
                    Some("进行中"),
                    Some("#1677ff"),
                    vec![],
                    vec![],
                    vec![],
                    None,
                ),
                "<p>当前进度：第 3 章「程序的机器级表示」。</p>",
                vec![
                    subtask(6, 6, "完成第 3 章阅读", false, 0),
                    subtask(7, 6, "整理本章笔记", false, 1),
                ],
            ),
            todo(
                summary(
                    7,
                    "更新个人简历",
                    "补充近期项目成果，优化项目描述与技能关键词。",
                    false,
                    "medium",
                    None,
                    Some(&date(20)),
                    Some(3),
                    Some("学习"),
                    Some("#722ed1"),
                    6,
                    false,
                    "自己",
                    None,
                    None,
                    None,
                    vec![],
                    vec![],
                    vec![],
                    None,
                ),
                "<p>需更新：Todo List 桌面端项目、数据迁移与提醒模块相关经历。</p>",
                vec![],
            ),
            todo(
                summary(
                    8,
                    "缴纳第三季度物业费",
                    "通过物业 App 完成缴费并保存电子凭证。",
                    false,
                    "medium",
                    Some(&date(5)),
                    Some(&date(12)),
                    Some(2),
                    Some("生活"),
                    Some("#52c41a"),
                    7,
                    false,
                    "自己",
                    Some(3),
                    Some("待验收"),
                    Some("#52c41a"),
                    vec![],
                    vec![],
                    vec![],
                    None,
                ),
                "<p>金额以物业通知为准，缴费后截图存档。</p>",
                vec![],
            ),
            todo(
                summary(
                    9,
                    "整理客户反馈并输出改进清单",
                    "汇总近两周用户反馈，按优先级整理改进项。",
                    true,
                    "medium",
                    Some(&date(-10)),
                    Some(&date(-1)),
                    Some(1),
                    Some("工作"),
                    Some("#1677ff"),
                    8,
                    false,
                    "自己",
                    Some(3),
                    Some("待验收"),
                    Some("#52c41a"),
                    vec![3],
                    vec!["会议"],
                    vec!["#13c2c2"],
                    None,
                ),
                "<p>已完成初版清单，待产品负责人确认后归档。</p>",
                vec![],
            ),
            todo(
                summary(
                    10,
                    "端午家庭聚会采购",
                    "采购水果、茶叶与礼盒，农历五月初五前完成。",
                    false,
                    "low",
                    Some(&date(3)),
                    Some(&date(25)),
                    Some(2),
                    Some("生活"),
                    Some("#52c41a"),
                    9,
                    false,
                    "自己",
                    Some(1),
                    Some("待办"),
                    Some("#8c8c8c"),
                    vec![],
                    vec![],
                    vec![],
                    Some(RecurrenceConfig {
                        enabled: true,
                        freq: "yearly".into(),
                        interval: 1,
                        anchor: "dueDate".into(),
                        calendar: "lunar".into(),
                        lunar_month: Some(5),
                        lunar_day: Some(5),
                        is_leap_month: Some(false),
                        first_reminder_date: None,
                        time: "08:30".into(),
                        advance_minutes: 1440,
                        on_complete: "reschedule".into(),
                    }),
                ),
                "<p>采购清单：粽子礼盒、水果篮、茶叶。</p>",
                vec![],
            ),
        ],
        settings: HashMap::new(),
    }
}
